### ISSUE TITLE
Querying target properties

### ISSUE THREAD

**Issue by jackgerrits** [alexcrichton/cmake-rs#100]
Hi, 

This is a pretty big ask, so I am mostly curious if this is something you've thought about.

I am using this crate to build a native lib to then link onto my rust project. This native lib can be used as a shared object, and statically link the private dependencies. However, I wanted to experiment with the [link time optimization opportunities](https://doc.rust-lang.org/rustc/linker-plugin-lto.html), but my compiling and linking the lib statically I am left with plenty of undefined references at link time. 

Do you know of a reasonable way to deal with this? Am I totally off track? My thoughts were that ultimately CMake is the thing resolving these dependencies for the native lib and so, it may make sense to lean on CMake to query for these libs in the `build.rs` file from the CMake target properties?

I would be interested in helping with this change if it seems like a direction that is worth following?

**Comment by alexcrichton** [comment]
Ah unfortunately I don't know much about cmake target properties or how to read them. It may be possible to expose here, but I haven't thought about this at all :(

**Comment by jackgerrits** [comment]
I was more just curious if you had thought about it, no problem!

Are there any best practices about adding link time dependencies for a native C++ lib in a Rust project? Are you aware of projects that do this?

**Comment by alexcrichton** [comment]
I've not personally done much with cross-langugae LTO myself, sorry :(

**Comment by jackgerrits** [comment]
It's no problem, this library is already immensely helpful and made it possible to have the C++ project built in build.rs. So, thank you! I am not sure if CMake has the capability to do this as something externally driving it compared to a CMake script itself.
