### ISSUE TITLE
Linker search path troubles

### ISSUE THREAD

**Issue by raymanfx** [alexcrichton/cmake-rs#103]
I'm on Fedora 32.

This is my FFI crate wrapping a (vendored) C/C++ library: https://github.com/raymanfx/openpnp-capture-rs/tree/master/sys.
I took the linker instruction from the cmake crate examples (see https://github.com/raymanfx/openpnp-capture-rs/blob/master/sys/build.rs#L17).

`cargo build` says: `error: could not find native static library 'openpnp-capture', perhaps an -L flag is missing?`.
The full rustc command invoked by cargo looks like this:
```
Running 'rustc --crate-name openpnp_capture_sys --edition=2018 sys/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="cc"' --cfg 'feature="cmake"' --cfg 'feature="default"' --cfg 'feature="vendor"' -C metadata=705474920d98c929 -C extra-filename=-705474920d98c929 --out-dir /home/chris/work/uni/rs/openpnp-capture/target/debug/deps -C incremental=/home/chris/work/uni/rs/openpnp-capture/target/debug/incremental -L dependency=/home/chris/work/uni/rs/openpnp-capture/target/debug/deps -L native=/home/chris/work/uni/rs/openpnp-capture/target/debug/build/openpnp_capture_sys-d3fa18c1ce2e7611/out -l static=openpnp-capture'
```

Changing the line in `build.rs` to: `println!("cargo:rustc-link-search=native={}/lib64", out.display());` fixes the issue (that path is where the actual lib resides).

Is this an issue on my side? Surely hardcoding/detecting `lib` vs `lib64` multilib paths cannot be the correct solution here.

**Comment by alexcrichton** [comment]
Yes this crate only builds the code, it doesn't print out link lines right now.
