### ISSUE TITLE
Parallelizing builds

### ISSUE THREAD

**Issue by MoAlyousef** [alexcrichton/cmake-rs#106]
Hello
Thanks for the amazing work. 

I noticed that the cmake crate tries to parallelize jobs using the NUM_JOBS environment variable. This is currently undocumented. It’s also possible to query the cmake version and pass the —parallel option to cmake (> 3.14), for older cmakes, querying nprocs and equivalents, can make building faster by default.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this in theory should already be working for makefiles, but is the parallel support not working for you? (or perhaps with a different build system)? Or is this about modernizing the support to pass the `--parallel` flag?

**Comment by MoAlyousef** [comment]
NUM_JOBS already works well with makefiles. However going with parallel doesn't need specifying how many jobs to pass, it also works well with visual studio generated projects. So I guess it's about both.

**Comment by alexcrichton** [comment]
Sorry I'm still a bit confused about what the issue is here. Does visual studio *not* get parallelized?

The `NUM_JOBS` flag is intended to limit parallelism so it's not something we'd want to ignore as a build-dependency of a Cargo library. Are you using this create outside of a Cargo build script context though?

**Comment by MoAlyousef** [comment]
I don't think it does. 
Apparently to enable multiprocessor builds in visual studio, the ```/MP``` flag is needed. In the lib.rs I see an m flag being passed instead.

**Comment by alexcrichton** [comment]
Ah ok, that does seem like an issue! I wonder if `cc` should pass that flag as well... In any case sounds like a PR should be able to fix this!

**Comment by MoAlyousef** [comment]
I've created a pull request #107 
I also query the cmake version to be able to pass the --parallel flag which doesn't need a NUM_JOBS value. I've tried it locally and the build times were reduced by half. If you prefer not passing the flag automatically I can remove it.
