### ISSUE TITLE
Add Config option for OUTPUT_NAME?

### ISSUE THREAD

**Issue by OJFord** [alexcrichton/cmake-rs#109]
Whether as a `cmake::Config::new("foo").set_property(prop, val)` or more specific `.output_name(val)`, it would be handy to be able to set the [`OUTPUT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/OUTPUT_NAME.html) - presently I'm running `cmake::build("foo")` and then having to `fs::copy("foo/foo", format!("foo/foo-{}", env::var("TARGET")?))` in order for Tauri to pick it up as the correct build for the current target.

Maybe in most cases this is under the user's control since it can be set in CMakeLists.txt or wherever (I confess I don't really know cmake!) - but I'm compiling a third party binary, using it's own configure script, so I don't want to and can't cleanly mess with it.

**Comment by alexcrichton** [comment]
Feel free to send a PR for this!

**Comment by OJFord** [comment]
I've had a bit of a look at this, it seems CMake has independent concepts of 'variables', and 'properties'; the latter sub-divided into a number of scopes. `OUTPUT_NAME` is a property, specifically with the 'target' scope (makes sense - output per target).

It seems that all the.. let's call them options, set today in cmake-rs are _variables_, e.g. `-DCMAKE_BUILD_TYPE`.

As far as I can tell there isn't an equivalent CLI flag for setting properties. There is [`set_property`](https://cmake.org/cmake/help/latest/command/set_property.html?highlight=set_property), (and `set_target_property`) but that is to be used in a makefile (err, CMakeLists.txt?).

I'm not sure that it would be appropriate for cmake-rs to modify this file, or even to somehow merge its own configuration in with it (I looked for but didn't find a built-in way, but assuming commands can simply be appended this could be done in memory or with a temp file)? So unless I've missed a flag, I'm not sure how possible this is, unfortunately.

(An option specifically for `OUTPUT_NAME` though might be to pretend to support it, or not, but either way do nothing more intelligent than simply moving the real output to wherever's requested, as I'm currently doing with `fs::copy` after `cmake::build`.)

**Comment by alexcrichton** [comment]
Ok in that case yeah seems like this crate can't do this. I would prefer to not get into the business of editing files if possible, but that can always be built as a separate crate!
