### ISSUE TITLE
Windows/MSVC quirk

### ISSUE THREAD

**Issue by photex** [alexcrichton/cmake-rs#12]
Howdy howdy!

https://github.com/alexcrichton/cmake-rs/blob/master/src/lib.rs#L379

This is fine on most machines, but I was plopped into trouble once I tried to do some work on a machine with a non-standard installation location. I forked and am testing but want to get a gut check first.

I was going to start using the version reported by cl.exe instead of it's location first. Are there some other ideas I should try? Environment variables perhaps?

**Comment by alexcrichton** [comment]
Thanks for the report! I wonder if there's perhaps some registry keys akin to what gcc-rs uses which we could scrape? But yeah relying on a particular string showing up in the path probably isn't a great idea :(

**Comment by photex** [comment]
What's funny is that in my case it would have worked out but I removed the '.0' from version number (c:\VisualStudio\14\...). :)

I'll play around with using the registry first. There are a couple of pages that seem to be a good place to start: 
https://msdn.microsoft.com/en-us/library/bb164659.aspx?f=255&MSPPError=-2147217396
http://www.mztools.com/articles/2008/MZ2008003.aspx

**Comment by alexcrichton** [comment]
Because the CMake generators are hard coded we probably don't even need to get too fancy. If we're just detecting the presence of various VS installs, we could just check for specific registry keys and call it a day

**Comment by photex** [comment]
o/

So I'm going a bit cross-eyed here. If I only scan for keys without taking the environment into account then I have the problem that I might select an inappropriate generator for the current environment.
For instance, I have versions 12.0, 14.0, and 15.0 installed but I'm working in the environment for 14.0 I want to be sure that I get the appropriate toolchain then. When you have the environment initialized in the shell on windows there will be a specific environment variable set `VisualStudioVersion` which going on the example is '14.0' as you'd expect.
If you haven't setup the dev env then that wouldn't be present and certainly shouldn't affect the generation of cmake target with a suitable default (highest version detected?)... of course you'll have trouble linking I think.. but that another detail.

I'm looking at gcc-rs here too in order to understand how these choices are getting made there.

So what if first, we check for that environment variable, if that isn't present then we check for supported versions under one of the following keys in the registry:

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\<version>
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\vs\Servicing\<version>

Taking the highest supported version found. Essentially first see if a key for 14.0 exists then 12.0?

**Comment by alexcrichton** [comment]
Yeah that sounds good to me, if a specific shell is activated we should for sure use that one first and then if that fails we should pick the highest possible.

**Comment by photex** [comment]
Closing this since we have a PR in progress.
