### ISSUE TITLE
Project is rebuilt from scratch every time

### ISSUE THREAD

**Issue by Storyyeller** [alexcrichton/cmake-rs#13]
I used cmake::build in my build.rs script, but I noticed that it does the build from scratch every time, even though the underlying files haven't changed. At the top of my output, I see

detected home dir change, cleaning out entire build directory

Is there a way to fix this?

**Comment by Storyyeller** [comment]
I figured out the problem

cmake-rs does a substring search on CMAKE_HOME_DIR for the path you give it, but it doesn't cannonicalize the path first

I was doing
cmake::build("../..")

but obviously "../.." doesn't appear in the cmakecache - the cache stores the actual file path. 

I was able to workaround this by instead doing
cmake::build(fs::canonicalize("../..").unwrap())

**Comment by alexcrichton** [comment]
Ah yeah that'd do it! I'd be more than ok doing this internally as well, would you be interested in sending a PR?

**Comment by Storyyeller** [comment]
Just created a PR. I didn't actually test it, but it should work.

**Comment by alexcrichton** [comment]
Fixed in #14
