### ISSUE TITLE
Why can’t we have debug info on MSVC?

### ISSUE THREAD

**Issue by chris-morgan** [alexcrichton/cmake-rs#19]
[`src/lib.rs`, in `Config.build`](https://github.com/alexcrichton/cmake-rs/blob/20064d7d30f22ef629885def64d2f6416c484cb1/src/lib.rs#L295-302):

```rust
        let profile = self.profile.clone().unwrap_or_else(|| {
            match &getenv_unwrap("PROFILE")[..] {
                "bench" | "release" => "Release",
                // currently we need to always use the same CRT for MSVC
                _ if msvc => "Release",
                _ => "Debug",
            }.to_string()
        });
```

I *need* debug info for something I’m making now for which I’m using MSVC. Why is this library forcing debug mode for MSVC? As it is, I suppose I’ll be hackily substituting this crate.

**Comment by alexcrichton** [comment]
PRs welcome! I'd recommend testing locally to be sure it works.

**Comment by lilianmoraru** [comment]
@chris-morgan The API offers you the option to change this default. Call `.profile`.

**Comment by jethrogb** [comment]
@lilianmoraru as you can see from the code that @chris-morgan quoted, that is ignored in MSVC mode.
