### ISSUE TITLE
C++ builds not properly accounted for

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/cmake-rs#2]
The `Config` builder sets `CMAKE_C_FLAGS` to add things like `-fPIC`, but does not set `CMAKE_CXX_FLAGS` in the same way so C++ builds fail to link. Same deal with `CMAKE_C_COMPILER`.

**Comment by alexcrichton** [comment]
Added in https://github.com/alexcrichton/cmake-rs/commit/25f8dc37f1de746b8f0ce0395d78b7a750cffe6d
