### ISSUE TITLE
CMake configure & build cache?

### ISSUE THREAD

**Issue by kkimdev** [alexcrichton/cmake-rs#20]
It looks like CMake is configured and built(null build) even when it's not changed from the previous build.  I guess it's good to have it cached?

**Comment by alexcrichton** [comment]
It may have been historical versions of cmake but I've had lots of problems in the past of cmake choking on updating the a project while using an old build directory. In light of that I added this behavior by default to just blow everything away, relying on Cargo to provide incremental builds.

I'd be totally down for having an option here or possibly changing the default to not blow everything away.

**Comment by aloucks** [comment]
This line seems to cause problems, at least when running from an mingw shell. 
https://github.com/alexcrichton/cmake-rs/blame/master/src/lib.rs#L533

Checking `line.contains("CMAKE_HOME_DIRECTORY") && !line.contains(src)` doesn't seem to be sufficient. 

CMakeCache.txt:
```
CMAKE_HOME_DIRECTORY:INTERNAL=G:/projects/project
```
I think it needs to parse out the text after the `=` and canonicalize the value before comparing it to `src`.

```rust
fn main() {
    println!("{}", fs::canonicalize("G:/projects/project").unwrap().display());
}
```
Results in:
```
\\?\G:\projects\project
```

**Comment by alexcrichton** [comment]
@aloucks oh that's a good point! Seems like we should just canonicalize both paths  I think? Want to send a PR?

**Comment by nox** [comment]
This can be closed, I think.

**Comment by alexcrichton** [comment]
Indeed!
