### ISSUE TITLE
Release builds get compiled with -O0

### ISSUE THREAD

**Issue by dotdash** [alexcrichton/cmake-rs#21]
In cmake-rs 0.1.19, the `Release` configuration in the generated CMake build is set to compile with `-O0` which is rather unfortunate ;-)

I guess this is a side-effect of https://github.com/alexcrichton/cmake-rs/commit/02266792b55420988f179be99cdbd18f29da2545, setting `CMAKE_CXX_FLAGS_RELEASE`, containing the `-O0` generated by the gcc crate.

**Comment by alexcrichton** [comment]
Thanks for the report!

**Comment by dotdash** [comment]
Sorry, I described the problem badly. it's not just that `-O0` is contained in the `CMAKE_CXX_FLAGS_RELEASE`, but also that the current approach just completely overrides the defaults set by the project. So with the commit that was supposed to fix this, `-O0` is gone, but now there's simply no `-O` option at all, so it's still building without optimizations.

Since `cmake -DYADDA=YADDA` seems to be unable to just append to a variable, the only workaround I see is to create a custom cmake script and feed that to cmake using the `-P` option.

**Comment by alexcrichton** [comment]
Ugh well isn't that just great... I'll look more into this.

**Comment by alexcrichton** [comment]
Ok, I've set it to only happen for Visual Studio builds now -- https://github.com/alexcrichton/cmake-rs/commit/8824d5ada39b22d4bd797febab7bc7bf7a794881
