### ISSUE TITLE
cross compiler path is not set correctly

### ISSUE THREAD

**Issue by bgermann** [alexcrichton/cmake-rs#36]
Current cmake versions ignore the -DCMAKE_{C|CXX}_{COMPILER|FLAGS} options and warn about them being ignored:

>  Manually-specified variables were not used by the project:
>
>    CMAKE_CXX_COMPILER
>    CMAKE_CXX_FLAGS

If you are cross compiling with a prefixed compiler, the linking will fail as the build system's compiler is used for the build.

Workaround: Set CC environment variable.

**Comment by alexcrichton** [comment]
What's the recommended way to set the compiler for c++/cmake?

**Comment by bgermann** [comment]
In [their FAQ](https://cmake.org/Wiki/CMake_FAQ#How_do_I_use_a_different_compiler.3F) the environment variables CC and CXX are mentioned as Method 1. Method 2 is your current approach, which seems outdated to me as cmake ignores the flags.

**Comment by alexcrichton** [comment]
Ok! Sounds like it shouldn't be to hard of a patch to implement this
