### ISSUE TITLE
--target is not always a valid command

### ISSUE THREAD

**Issue by valarauca** [alexcrichton/cmake-rs#37]
For example Google's BoringSSL can't be build with this crate as it `--target` isn't a valid `cmake` command for it.

I don't know how to disable it but the default of `--target "install"` causes a build error.

**Comment by alexcrichton** [comment]
Interesting! Maybe we could add an option like `no_build_target` which disables passing the `--target` flag to cmake?

**Comment by valarauca** [comment]
That should work.

I guess the only other approach would be an `Option<String>`, but that would be an api change.

:+1:

**Comment by alexcrichton** [comment]
Yeah we can probably do that eventually but for now stick with the backwards compatible option. Would you be willing to send a PR to test this out?

**Comment by valarauca** [comment]
Currently traveling I'll try to submit soon.

**Comment by alexcrichton** [comment]
Ok, thanks!
