### ISSUE TITLE
Linking against system libraries

### ISSUE THREAD

**Issue by spacekookie** [alexcrichton/cmake-rs#41]
So I've been fiddling around with this for a few hours now and can't really figure it out.

I have a component written in C which uses [this CMakeLists file](https://github.com/spacekookie/luadns/blob/master/CMakeLists.txt) which also builds properly. And then I want to link that library in my [build.rs](https://github.com/spacekookie/ddos/blob/master/build.rs) which also works.

The problem is that the C component (`luadns`) depends on `libluajit-5.1` and when I build and link via cargo I get `undefined reference to 'luaL_newstate'` errors (and similar) for every call to the external system library.

I'm a bit at a loss how to fix this so I hope you can help me get this to work :heart:

**Comment by alexcrichton** [comment]
Ah so right now this crate doesn't actually print out any linkage annotations, you'll need to manually do linkage like:

```rust
println!("cargo:rustc-link-lib=static=foo");
```

(or omit `static=` if it's a dynamic library)

**Comment by spacekookie** [comment]
Hey there. I mean, I'm already doing that in my `script.rs`:

```
    let dst = cmake::build("libluadns");
    println!("cargo:rustc-link-search=native={}", dst.display());
    println!("cargo:rustc-link-lib=static=luadns");
```

Or do you mean I would have to link against `luajit-5.1` (which is what I depend on system library wise) like that as well? Wouldn't that mean that I have to duplicate all the linking done by the cmake setup inside my `build.rs`? 

If I seem confused...that's because I am 😝

**Comment by alexcrichton** [comment]
Ah yeah you'll want to link to `luajit-5.1` as well (assuming `libluajit-5.1.so` is on the system), and I think you'll want to be sure to print that out before you print `luadns`. Does it work if you do that?

**Comment by spacekookie** [comment]
Hmmm....that complains even though `/usr/lib/libluajit-5.1.so` exists. I thought it might have something to do with library search scope so I added `println!("cargo:rustc-link-search=native=/usr/lib")` but that didn't end up any difference 😞 

Any other ideas?

**Comment by alexcrichton** [comment]
What's the error message you're seeing when you try to run it or when the link fails?

**Comment by spacekookie** [comment]
What I'm getting is the following

```
 ❤ (rayya) ~/P/c/ddos> cargo build                                                          (master|✚4…) 
   Compiling ddos v0.1.0 (file:///home/spacekookie/Projects/code/ddos)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/spacekookie/Projects/code/ddos/target/debug/deps/ddos-3d99762363d50f0c.ddos0.rust-cgu.o" "/home/spacekookie/Projects/code/ddos/target/debug/deps/ddos-3d99762363d50f0c.ddos1.rust-cgu.o" "-o" "/home/spacekookie/Projects/code/ddos/target/debug/deps/ddos-3d99762363d50f0c" "/home/spacekookie/Projects/code/ddos/target/debug/deps/ddos-3d99762363d50f0c.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/spacekookie/Projects/code/ddos/target/debug/deps" "-L" "/usr/lib" "-L" "/home/spacekookie/Projects/code/ddos/target/debug/build/ddos-7672b70394d12199/out" "-L" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "luajit-5.1" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-l" "luadns" "-Wl,--no-whole-archive" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3d93d262ece22666.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-09422e80459746d9.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-175e52254a69ae20.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-63a902616a5c66d8.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a0dcd45e686d8f52.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-0affd40357478cee.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6921f2e2e6a20026.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-edd2f2fb3716a8bc.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-9c42fe44e27bb617.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-01a2d7d2b8b6e945.rlib" "/home/spacekookie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-497d24d6ca148a36.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util"
  = note: /usr/sbin/ld: cannot find -lluajit-5.1
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error
```

Sorry, should have posted the log before but I had visitors and was kinda in a hurry. This is the build.rs I'm using with it:

```rust
fn main() {
    let dst = cmake::build("libluadns");
    println!("cargo:rustc-link-search=native=/usr/lib");
    println!("cargo:rustc-link-lib=static=luajit-5.1");
    println!("cargo:rustc-link-search=native={}", dst.display());
    println!("cargo:rustc-link-lib=static=luadns");
}
```

It just looks like `-lluadns-5.1` is failing where it shouldn't. Just building the library with a cmake file manages to link `luadns-5.1`. That makes me think that it's library scope path isn't correct or something like that...

**Comment by alexcrichton** [comment]
Oh that error means that the luajit-5.1 library can't be found by the linker, so are you sure the `rustc-link-search` path is correct? Does /usr/lib/libluajit-5.1.so exist a s a file?

**Comment by spacekookie** [comment]
Yes, 100% certain. See below

```
 ❤ (rayya) ~> ll /usr/lib/libluajit-5.1.so*                                                 
lrwxrwxrwx 1 root root   22 May  6  2017 /usr/lib/libluajit-5.1.so -> libluajit-5.1.so.2.0.5*
lrwxrwxrwx 1 root root   22 May  6  2017 /usr/lib/libluajit-5.1.so.2 -> libluajit-5.1.so.2.0.5*
-rwxr-xr-x 1 root root 452K May  6  2017 /usr/lib/libluajit-5.1.so.2.0.5*
```

That's what's puzzeling me so much 😕

**Comment by alexcrichton** [comment]
Oh! You're printing out `static=luajit...` when I think it should just be `luajit...` (omitting the `static=`)

**Comment by spacekookie** [comment]
Yay that worked! Although it adds another error that puzzles me a little, especially after some experimenting:

```
.../luadns.c:681: undefined reference to `luaL_newstate'
.../luadns.c:682: undefined reference to `lua_close'
```

Those are functions that should be exposed by `libluajit-5.1.so` and that link properly when using the cmake build. 

Looking at the `build.rs` I posted above, if removing the last two lines (and the line in main.rs that calls into luadns) it builds. Could this have to do something with the second path scope overriding the first or something? I don't really know how those lines work anyways so I can only guess here.

Thanks for your support with this already ❤️

**Comment by alexcrichton** [comment]
I think you'll want to change the ordering. I forget which way is which but if you print out luadns and luajit-5.1 in different orders I think it may fix the issue

**Comment by spacekookie** [comment]
Oh yay, yes it does 🎉 

... Why? As I mentioned, I don't really understand how printing something in the build.rs then changes how it's linked.

In either case, mind if I added some documentation about this? (Mostly a more complicated example, because even without these issues, I had some problems figuring out what to do)

**Comment by alexcrichton** [comment]
> ... Why? 

Heh, this is the rabbit hole of "how linkers work". Linkers (not `cc`, what it invokes under the hood, `ld`) on Linux/OSX tend to work in a "left to right" fashion. What happens is that each of the inputs on the command line will provide a number of symbol definitions for the output artifact (the executable or dynamic library) but also depend/import on a number of symbols. The linker walks each command line argument one-by-one doing:

* If it's an object file (`foo.o`) then it's pulled in, defining new symbols and adding to the list of unresolved symbols.
* If it's an archive (`libfoo.a`) then it's pulled in *only* if it resolves an undefined symbol. Even then, only the objects in the archive resolving those undefined symbols are pulled in (each archive can have multiple object files inside it)
* If it's a shared library (`libfoo.so`) then it's also only pulled in if it resolves an undefined symbol

So what happened here is that the failing linker was executing with `-lluajit-5.1 -lluadns`. By the time the linker considered `-lluajit-5.1` there were no unresolved symbols that it satisfied, so the linker discarded the argument and library. Then the linker processed `-lluadns` and pulled it in (presumably because your Rust code referenced symbols inside there). That added new unresolved symbols like `luaL_newstate` (presumably defined in `libluajit-5.1.so`). The linker didn't go back and figure that out, so it generated a link error.

By switching the order of the println in Rust you switch the order rustc passes them to the linker, which is why `-lluadns -lluajit-5.1` works. In that case the `luadns` library is pulled in first, `luaL_newstate` is an unresolved symbol, and when considering `luajit-5.1` the linker actually pulls it in this time because `luaL_newstate` is a symbol inside there that it resolves (I think at least, I don't know for sure as I don't have the library myself)

> In either case, mind if I added some documentation about this? 

Sure! Although I'm not entirely sure how much to convey. Unfortunately linker errors are sort of a cliff where if you can't fix it in the first 30 seconds you basically need to read a book on linkers to see how to fix it. If you've got an idea of what to document though, I'd love to add some words!

**Comment by spacekookie** [comment]
Alright, thanks a ton: 😄 For now I can work on my project again.

When it comes to documentation I'll give this a thought for a while and maybe come up with something. In general I think this crate could use a few more lines of docs. This is coming from me as a Rust noob who was suuuper confused by how to use any of this where a few more lines of example would have helped considerably.

But closing this issue for now as it was resolved :)
