### ISSUE TITLE
RelWithDebInfo and MinSizeRel cmake standard build types are not supported

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/cmake-rs#51]
CMAKE_BUILD_TYPE supports Debug, Release, RelWithDebInfo and MinSizeRel.

If the build type is Rust's `release`, and `-C debuginfo=0` then `cmake-rs` should use `Release`, and if `-C debuginfo != 0` then it should use `RelWithDebInfo`. 

If the Rust build-type is `release` but optimizing for size then `cmake-rs` should use `MinSizeRel`.

**Comment by alexcrichton** [comment]
Seems reasonable to me to infer! I think we can for sure use the env vars to detect these sorts of builds

**Comment by gnzlbg** [comment]
A weird naming issue is that the `set_profile` method actually sets CMake's `CMAKE_BUILD_TYPE` variable. It might be clearer to deprecate that and provide a different method called `set_build_type`.
