### ISSUE TITLE
Weird issue when building rustc

### ISSUE THREAD

**Issue by steveklabnik** [alexcrichton/cmake-rs#60]
I'm setting up a brand new computer, so it's time to build rustc! I've installed MSVC 2017, and 

When doing so, I get a 

    couldn't determine visual studio generator
    if VisualStudio is installed, however, consider running the appropriate vcvars script before building this crate

If I run vcvars, nothing changes. Same failure.

If I build rustc inside of the Developer Command Prompt, it ~~builds just fine.~~ gets further but fails for other reasons.

This *might* be a rustc bug bug I figured I'd file it here first... any ideas?

**Comment by alexcrichton** [comment]
Ah this crate actually [just delegates](https://github.com/alexcrichton/cmake-rs/blob/f7506ef71ce91eef8ddf90206996b0db60ff47b8/src/lib.rs#L676-L686) to the `cc` crate. That crate's detection of MSVC tools and such is super gnarly and surely bug prone with various flavors of MSVC installations. Want to move the issue over there though and I can try to tag other folks in?

(`cc` is used for all rustc-related MSVC detection as well, so this failing probably means that `rustc` will fail as well)

**Comment by steveklabnik** [comment]
Done
