### ISSUE TITLE
File src/lib.rs has executable bit set

### ISSUE THREAD

**Issue by silwol** [alexcrichton/cmake-rs#61]
Usually source files should not be executable. The `src/lib.rs` file has the executable bit set, and that property also gets distributed through the downloads from crates.io. I stumbled upon this problem when attempting to update the cmake-rs Debian package, because the lintian tool shows a warning for that.
I assume it's impossible to modify the already-distributed version on crates.io, but it would help for future versions.

**Comment by alexcrichton** [comment]
Oops, thanks for the heads up!
