### ISSUE TITLE
Ignore warnings

### ISSUE THREAD

**Issue by calebmer** [alexcrichton/cmake-rs#7]
Currently I'm trying to use this tool to make Facebook's [`libgraphqlparser`](https://github.com/graphql/libgraphqlparser), however the process generates a few errors which can be safely ignored. I know this as running a plain `cmake .` has the intended behavior. I've included the output when using `cmake::build` from a `build.rs` file below.

I'm not too familiar with `cmake`, but my intuition is that the two warnings: one from an optional python example included in the repo and the other from what the message calls policy `CMP0042` (which also appears to be a suppressible warning). These two warnings cause an exit code of 2 (again, just my guess) which causes the rust thread to panic.

```
failed to run custom build command for `graphql-parser v1.0.0 (file:///Users/calebmer/Projects/calebmer/graphql-parser)`
Process didn't exit successfully: `/Users/calebmer/Projects/calebmer/graphql-parser/target/debug/build/graphql-parser-011a4a5e2db17d79/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/Users/calebmer/Projects/calebmer/graphql-parser/libgraphqlparser" "-DCMAKE_INSTALL_PREFIX=/Users/calebmer/Projects/calebmer/graphql-parser/target/debug/build/graphql-parser-011a4a5e2db17d79/out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Could NOT find BISON: Found unsuitable version "2.3", but required is at least "3" (found /usr/bin/bison)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/calebmer/Projects/calebmer/graphql-parser/libgraphqlparser
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--" "-Wno-dev"

--- stderr
CMake Warning at python/CMakeLists.txt:13 (MESSAGE):
  ctypesgen.py not found; install with pip or easy_install if you want to run
  pythontest.py.


CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   graphqlparser

This warning is for project developers.  Use -Wno-dev to suppress it.

make: *** No rule to make target `install'.  Stop.
thread '<main>' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/calebmer/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/cmake-0.1.16/src/lib.rs:448
```

**Comment by alexcrichton** [comment]
Ah I think the error here is that this library attempts to run the `install` target rather than just a normal build target (to install the various libraries). You can override this through the [`build_target`](http://alexcrichton.com/cmake-rs/cmake/struct.Config.html#method.build_target) method which should do the trick!

**Comment by calebmer** [comment]
Where would I look for the correct `build_target`? I looked around and I assume it's talking about `Makefile` build targets, so I changed the `build_target` to a couple of targets defined in the `Makefile` and got the same error.

As another note, `install` *is* a target in the `Makefile`.

**Comment by alexcrichton** [comment]
Weird, maybe this is trying some cmake-specific target rather than a literal makefile target?

**Comment by calebmer** [comment]
How would I tell? Or how would I test cmake targets?

**Comment by alexcrichton** [comment]
You can try running cmake manually in the project and see what arguments to `--target` produce a successful build perhaps?

**Comment by calebmer** [comment]
The command `cmake --build . --target install --config Debug` in the `libgraphqlparser` directory (not the directory which contains it with the `build.rs` file) successfully installs.

**Comment by alexcrichton** [comment]
From the build script, looks like an extra argument may be getting erroneously passed then?

```
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--" "-Wno-dev"
[..]
make: *** No rule to make target `install'.  Stop.
```

**Comment by calebmer** [comment]
If you are talking about `-Wno-dev`, I've tried with and without attempting to quiet one of the warnings in the OP.

**Comment by alexcrichton** [comment]
Note that the warnings are likely red herrings here, the build isn't stopping because of that. The build is stopping because apparently the generated Makefile does not have the target `install`

**Comment by calebmer** [comment]
Ok, it was my best guess at the time 😊

The generated `Makefile` definitely has an `install` target (double checked and ran myself), and the project even [says](https://github.com/graphql/libgraphqlparser#building-libgraphqlparser) building the project requires `make install`. So I'm not sure what the issue actually is 😖

**Comment by calebmer** [comment]
Where does `cmake-rs` build and place the code? As a workaround I could have my own `Makefile` which runs the build steps and puts it in the same folder. At the moment, the `dst` variable in the examples is a black box to me.

**Comment by alexcrichton** [comment]
Right now this crate basically:

1. Runs `cmake` to configure the build
2. Runs [`cmake --build . --target ...`](https://github.com/alexcrichton/cmake-rs/blob/master/src/lib.rs#L344-L352)

The directory layout looks like:

* `$OUT_DIR/build` - build directory
* `$OUT_DIR/` - installation
