### ISSUE TITLE
What is the proper way to support Android in a rust library？

### ISSUE THREAD

**Issue by SchrodingerZhu** [alexcrichton/cmake-rs#94]
Recently, I am working on snmalloc-rs to
make it support Android cross compilation. 

https://github.com/SchrodingerZhu/snmalloc-rs/commit/09726c0ab61ff7e768022de885aae32336227a70

It seems that `target_os="android"` is not working here. Yet, current solution can only compile the library itself.  When another Android binary crate depends on this crate, the target static library compiled by cmake does not have the right architecture.

**Comment by alexcrichton** [comment]
`cfg!` is for the platform the build script is compiled for, which isn't the platform the build script is compiling for. You'll want to use the `TARGET` env var to make these sorts of decisions.
